# Generated by Django 5.1.4 on 2024-12-19 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_motive_id_alter_motive_logo_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False), max_length=50),
        ),
        migrations.AlterField(
            model_name='groupcontributor',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='initiatorgroupcontributor',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motive',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
