# Generated by Django 5.1.4 on 2024-12-19 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_proof', models.FileField(default=None, null=True, upload_to='files/documents/address_proof/')),
                ('address_proof_verified', models.BooleanField(default=False)),
                ('id_proof', models.FileField(default=None, null=True, upload_to='files/documents/id_proof/')),
                ('id_proof_verified', models.BooleanField(default=False)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
